name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [hola-mundo, funciones_api]  # Lista de aplicaciones

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'  # Ajusta la versión de Go según tus necesidades

    - name: Build and run Docker container
      run: |
        cd ${{ matrix.app }}  # Cambia al directorio de la aplicación
        docker build -t ${{ matrix.app }} .
        docker run --rm ${{ matrix.app }}
