name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app:
        description: 'Choose the application to run'
        required: true
        default: 'hello_world'  # App por defecto
        options:
          - hello_world
          - api_faas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Build and run Docker container
      run: |
        docker build -t ${{ github.event.inputs.app }} src/${{ github.event.inputs.app }}  # Especifica el directorio de la app
        docker run --rm ${{ github.event.inputs.app }}
