name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app:
        description: 'Choose the application to run'
        required: true
        default: 'hola-mundo'  # App por defecto
        options:
          - hola-mundo
          - funciones_api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build and run Docker container
      run: |
        cd ${{ github.event.inputs.app }}  # Cambia al directorio de la aplicación elegida
        docker build -t ${{ github.event.inputs.app }} .
        docker run --rm ${{ github.event.inputs.app }}
