 name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Choose the application to run (leave blank to run all)'
        required: false
        default: 'hello-world'
        type: choice
        options:
          - hello-world
          - api_faas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine Event Type
        id: event_type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "event_type=push" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "event_type=workflow_dispatch" >> $GITHUB_ENV
          fi

      - name: Get Changed Files
        id: changes
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            echo "changed_files=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV
          else
            echo "No previous commits found. No files to check."
            echo "changed_files=" >> $GITHUB_ENV
          fi

      - name: Filter Applications Based on Changes
        id: app_to_run
        run: |
          apps=("hello-world" "api_faas")
          changed_files=(${changed_files})
          filtered_apps=()
          
          echo "Changed files: ${changed_files[@]}"

          for file in "${changed_files[@]}"; do
            app_name=$(basename $(dirname "$file"))
            if [[ " ${apps[@]} " =~ " ${app_name} " ]]; then
              filtered_apps+=("$app_name")
            fi
          done
          
          if [ ${#filtered_apps[@]} -eq 0 ]; then
            echo "app_to_run=" >> $GITHUB_ENV
          else
            echo "app_to_run=${filtered_apps[@]}" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Images
        run: |
          build_and_push_docker_images() {
            input_apps=("hello-world" "api_faas")
            event_type="${{ github.event_name }}"
            echo "Event Type: $event_type"
            
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            if [ "$event_type" == "push" ]; then
              if [ -z "${{ env.app_to_run }}" ]; then
                echo "No relevant changes detected. Building and pushing all applications..."
                for app in "${input_apps[@]}"; do
                  echo "Building Docker image for: $app"
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/$app:latest ./src/$app
                  echo "Pushing Docker image for: $app"
                  docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
                done
              else
                echo "Relevant changes detected. Building and pushing only the specified applications..."
                for app in "${{ env.app_to_run }}"; do
                  echo "Building Docker image for only the specified application: $app"
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/$app:latest ./src/$app
                  echo "Pushing Docker image for: $app"
                  docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
                done
              fi
            elif [ "$event_type" == "workflow_dispatch" ]; then
              app_name="${{ github.event.inputs.app_name }}"
              echo "Selected application: $app_name"
              if [ -z "$app_name" ]; then
                echo "No application selected. Building and pushing all applications..."
                for app in "${input_apps[@]}"; do
                  echo "Building Docker image for: $app"
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/$app:latest ./src/$app
                  echo "Pushing Docker image for: $app"
                  docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
                done
              else
                echo "Building Docker image for only the selected application: $app_name"
                docker build -t ${{ secrets.DOCKER_USERNAME }}/$app_name:latest ./src/$app_name
                echo "Pushing Docker image for: $app_name"
                docker push ${{ secrets.DOCKER_USERNAME }}/$app_name:latest
              fi
            fi
          }

          build_and_push_docker_images
