name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app:
        description: 'Choose the application to run'
        required: true
        default: 'hello-world'
        options:
          - hello-world
          - api_faas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Debug- Show current directory and app path
      run: |
        echo "Current directory: $(pwd)"
        echo "App directory: src/${{ github.event.inputs.app }}"
        ls src/${{ github.event.inputs.app }}  # Listar el contenido para verificar si existe

    - name: Build and run Docker container
      run: |
        APP_DIR="src/${{ github.event.inputs.app }}"
        echo "Building Docker image from $APP_DIR"
        echo "Contents of $APP_DIR:"
        ls "$APP_DIR"  # Asegurarse de que el directorio tiene lo que se espera

        # Construir la imagen de Docker
        docker build -t "${{ github.event.inputs.app }}" "$APP_DIR"  # Especifica el directorio de la app
        docker run --rm "${{ github.event.inputs.app }}"
