name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Choose the application to run (leave blank to run all)'
        required: false
        default: 'hello-world'
        type: choice
        options:
          - hello-world
          - api_faas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Determine Event Type
        id: event_type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "event_type=push" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "event_type=workflow_dispatch" >> $GITHUB_ENV
          fi

      - name: Build and Run Applications
        run: |
          apps=("hello-world" "api_faas")
          
          if [ "${{ env.event_type }}" == "push" ]; then
            echo "Running all applications because of a push event..."
            for app in "${apps[@]}"; do
              echo "Building and running $app..."
              # Aquí podrías tener los comandos para compilar y ejecutar la app
            done
          elif [ "${{ env.event_type }}" == "workflow_dispatch" ]; then
            echo "Running selected application: ${{ github.event.inputs.app_name }}"
            if [ "${{ github.event.inputs.app_name }}" == "" ]; then
              echo "No application selected. Running all applications..."
              for app in "${apps[@]}"; do
                echo "Building and running $app..."
                # Aquí podrías tener los comandos para compilar y ejecutar la app
              done
            else
              echo "Building and running only the selected application: ${{ github.event.inputs.app_name }}"
              # Aquí podrías tener los comandos para compilar y ejecutar solo la app seleccionada
            fi
          fi
